export const INITIAL_INVENTORY = [
  {
    "id": "999999930",
    "item": "Cordless drill/driver (13mm chuck)",
    "brand": "Makita",
    "model": "DF457D (18V Li-ion)",
    "category": "Equipment",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/e21c6ea3-448c-449e-84a8-4e16b30551c3.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "4004722637250",
    "item": "Floor repair kit / laminate & wooden floor repair set (wax melt repair set)",
    "brand": "Werkzeyt",
    "model": "Bodenreparaturset (Floor repair set) â€” Code: B2769",
    "category": "Equipment",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/84e08e8c-cc59-4dcc-89f0-3d0d736635f9.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "999999929",
    "item": "WERCKMANN â€“ Professional Tools.",
    "brand": "WERCKMANN â€“ Professional Tools.",
    "model": "WERCKMANN â€“ Professional Tools.",
    "category": "Equipment",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/aca416e1-ee36-4d81-88e4-d8c12e6090ad.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8711247880172",
    "item": "Drill & bit set (Boren- & Bitset)",
    "brand": "GAMMA",
    "model": "101xâ€ â€” GAMMA â€œBoren- & Bitsetâ€ 101-piece",
    "category": "Equipment",
    "type": "Tool",
    "qty": 2,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/fc489bff-b942-4646-85c8-9e9e0a0d53bd.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "999999928",
    "item": "Electric space heater / fan heater (portable, tabletop)",
    "brand": "Sencys",
    "model": "Model No. 10390320 (NF20-18UR) Power/Specs: 220â€“24",
    "category": "Equipment",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/da8849fc-4cb6-4ef4-9c50-5568c637b8af.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "999999927",
    "item": "Electric finishing sander (sheet/palm sander)",
    "brand": "SKIL",
    "model": "SKIL 7280 (corded, 230V)",
    "category": "Equipment",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/2c2a71b5-e9ff-47a5-b9cf-1a3ac6ff8207.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "999999926",
    "item": "Paint spray gun (electric spray painter)",
    "brand": "HBM",
    "model": "HBM Spray Gun (electric spray system with paint cu",
    "category": "Equipment",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/1670112e-5cc4-475c-83e4-6009aabaf0a1.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8711247214083",
    "item": "Angle grinder (hand grinder)",
    "brand": "GAMMA",
    "model": "Haakse slijper HS-115HP (115mm disc)",
    "category": "Sealant",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/dc7f473c-03cf-46af-b273-de02ebb0c8df.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8710439259635",
    "item": "Sanitary silicone sealant (for bathroom/kitchen joints & sealing)",
    "brand": "Bison",
    "model": "Super Silicone â€” Sanitair (100% silicone)",
    "category": "Sealant",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/f722c9ff-4e8d-450a-811a-c39ef3a95743.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "5414628072953",
    "item": "Sanitary silicone sealant (for bathroom/kitchen joints & sealing)",
    "brand": "Sencys",
    "model": "Siliconenkit â€” Sanitair Universeel (Mastic silicon",
    "category": "Sealant",
    "type": "Consumable",
    "qty": 2,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/33538e5f-2666-4acb-9787-4baae45963a4.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "5400107576807",
    "item": "Hout & Vloer (Kit/Mastic) â€” Universele Houtkit (Classiek / Classique)",
    "brand": "Base Line",
    "model": "Acrylaatkit (Acrylic sealant / Mastic acrylique)",
    "category": "Sealant",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/28fdf72b-a287-4914-87ee-b13a2539271f.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "3146439086028",
    "item": "Wood & floor sealant / wood filler mastic (for laminate, parquet & wood)",
    "brand": "BISON",
    "model": "Hout & Vloer (Kit/Mastic) â€” Universele Houtkit (Cl",
    "category": "Sealant",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/4b0add07-4630-4202-86e1-6b906e302f61.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8011564251427",
    "item": "Miniature circuit breaker / installation automatic (MCB), B16 (16A), 1P+N, 6kA, 230V~",
    "brand": "GEWISS",
    "model": "GEWISS GW90328 (MCB installatieautomaat (nul) B16,",
    "category": "Electrical",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/6a99e593-996c-4143-9d12-20022a696b70.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8711247894537",
    "item": "Sandpaper roll (finishing) â€” grit P320",
    "brand": "GAMMA",
    "model": "Schuurrol â€œAfwerken / Finitionâ€ (finishing sandpap",
    "category": "Furniture and fixtures",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/e9bafd54-c663-44d8-9727-970e45b8248e.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "5010559436187",
    "item": "Digital moisture meter (pin-type) for wood & building materials",
    "brand": "Draper",
    "model": "Moisture Meter â€” 43618",
    "category": "Equipment",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/09ede061-d61c-444e-a5ad-09b8f6296ad4.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "4002593003068",
    "item": "Torque wrench set (click-type) with sockets and extension",
    "brand": "Powerfix Profi",
    "model": "DrehmomentschlÃ¼ssel-Set (torque wrench set) â€” 1/2\"",
    "category": "Equipment",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/53120e45-feaf-4402-b1c0-7d898216ccc5.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "999999925",
    "item": "Oil filter wrench/cap set (cup-style oil filter sockets) + 3-jaw oil filter wrench",
    "brand": "Wiltec Wildanger Technik GmbH",
    "model": "30-piece oil filter cap socket set (various sizes)",
    "category": "Equipment",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/7bcabc98-73ea-47c8-a030-6c23750c0abe.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "999999924",
    "item": "Electricians Toolbox / tool storage box (with organizer compartments)",
    "brand": "Patrol Group",
    "model": "Formula A700",
    "category": "Equipment",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/7c15bca2-b990-41fa-95db-4d0f95ef10f6.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "999999923",
    "item": "Folding try square / adjustable carpenterâ€™s square (metal angle ruler",
    "brand": "",
    "model": "Folding right-angle square with integrated spirit ",
    "category": "Equipment",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/a46c932e-2c75-4e29-b569-15de17bbd913.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "9999999221",
    "item": "Tube/box spanner wrench set (double-ended tubular wrenches)",
    "brand": "",
    "model": "Tubular wrench set â€” sizes: 8 mm, 10 mm, 12 mm, 13",
    "category": "Equipment",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/ca6f770d-8a99-4047-823b-4a9ffd054134.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "999999921",
    "item": "Electric impact wrench set (corded) with sockets & carry case",
    "brand": "Einhell",
    "model": "Einhell corded impact wrench (socket set included)",
    "category": "Equipment",
    "type": "Tool",
    "qty": 2,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/28a0ccd1-e904-4da5-b77a-29ffb3f6b465.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "999999920",
    "item": "L-square / carpenterâ€™s framing square (right-angle measuring ruler)",
    "brand": "MILWAUKEE",
    "model": "Metric framing square with angle/degree markings",
    "category": "Equipment",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/fd34de83-d3db-4aa7-9272-9becf6630734.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "999999919",
    "item": "Socket wrench set",
    "brand": "BrÃ¼der Mannesmann",
    "model": "215-piece socket set (SteckschlÃ¼sselsatz), Art.-Nr",
    "category": "Equipment",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/4917d605-0ddf-4143-bf70-344e54432ee7.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "999999918",
    "item": "Cordless circular saw (handheld)",
    "brand": "SKIL",
    "model": "20V Max (brushless-style housing) circular saw â€” b",
    "category": "Equipment",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/8faf3b5f-d79a-450b-b55c-e57b577e325b.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "4048962245639",
    "item": "Universal wall plug set (for solid + hollow walls incl. drywall/plasterboard)",
    "brand": "fischer",
    "model": "DUOPOWER (assorted plugs in carry case â€” â€œ280xâ€ se",
    "category": "Equipment",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/38e0be26-59c2-4ea4-b66c-4930c7618523.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8711247018551",
    "item": "Furniture glides / nail-on felt glides (white)",
    "brand": "HANDSON",
    "model": "24 pcs by 20mm",
    "category": "Equipment",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/16dbabe5-6974-403b-8924-8b8b0cc88a68.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "999999917",
    "item": "Wood chisel set",
    "brand": "Stanley",
    "model": "Chisel set â€“ 5 pcs",
    "category": "Equipment",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/fc8f2d10-d887-43fd-83d3-1cee9d7ff5cc.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8711969043466",
    "item": "Roundup AC Totaal weed killer (ready-to-use sprayer)",
    "brand": "Roundup",
    "model": "Roundup AC â€“ Onkruidvrij Totaal",
    "category": "Equipment",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/f3f597ed-c0ab-4cec-9886-f5cae2d58454.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8711332174117",
    "item": "Plastic wall plugs / drywall anchors (self-drilling type, coarse thread)",
    "brand": "",
    "model": "Self-drilling plastic â€œplasterboardâ€ anchor plugs ",
    "category": "Equipment",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/0eaedf96-dd27-4a29-ba7c-e12d9c1828f1.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "999999916",
    "item": "Mixed metal nuts & washers set (assorted hex nuts / fittings)",
    "brand": "",
    "model": "Assorted hex nuts + washers/spacers (various sizes",
    "category": "Equipment",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/f63b0b29-81f8-4ba0-9549-2276f170cd44.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "999999915",
    "item": "Measuring tape / tape measure (retractable)",
    "brand": "",
    "model": "Hand tape measure with locking button and belt cli",
    "category": "Equipment",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/8bc1b8e3-6455-4762-a807-07abb88f8774.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8711247058601",
    "item": "Curtain rail runners/gliders (for U-rail)",
    "brand": "GAMMA",
    "model": "Runners voor U-rail â€” wit â€” pack of 10",
    "category": "Equipment",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/f486a5e4-6f5e-4727-9d69-f901c6076ff1.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "999999914",
    "item": "Metal plasterboard anchors / drywall plugs (gipsplaatpluggen)",
    "brand": "GAMMA",
    "model": "Gipsplaatplug Ã˜ 7 mm (metaal) â€” pack of 8 Finish/C",
    "category": "Equipment",
    "type": "Tool",
    "qty": 3,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/72bf3192-aef1-4b6d-8171-576dfd8780c0.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "999999913",
    "item": "Heavy-duty extension cable / power extension lead (EU Schuko)",
    "brand": "",
    "model": "Long Schuko extension lead (male plug to female)",
    "category": "Equipment",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/42cb7dd2-2502-49d4-99b9-aefc9a881acb.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "999999912",
    "item": "3-socket extension lead / power strip with on/off switch (EU Schuko)",
    "brand": "IKEA",
    "model": "3-way Schuko extension block with rocker switch",
    "category": "Equipment",
    "type": "Tool",
    "qty": 2,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/471c8eee-316e-4d1d-879a-5b8401796b2b.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "9999999919",
    "item": "One-hand bar clamp / quick-grip clamp (trigger clamp)",
    "brand": "Werckmann (Professional Tools)",
    "model": "Quick-grip / one-hand clamp (ratchet bar clamp wit",
    "category": "Equipment",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/e700423e-b00d-4833-aa67-61cfe891b14d.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8717344993197",
    "item": "Suction lifter / suction cup handle (for lifting glass, tiles, smooth panels)",
    "brand": "Benson Tools",
    "model": "Super Zuignap (suction cup lifter) â€” 1 cup",
    "category": "Equipment",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/8e029093-6641-4718-94a0-3024a4910b7c.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8718546652257",
    "item": "Jumper cables / booster cables set (start cables) â€” for jump-starting vehicles",
    "brand": "TUV",
    "model": "Startkabelset 12/24V â€” 3m, 16mmÂ², 220A",
    "category": "Equipment",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/52947606-0611-475f-8e38-6be90ff5ea5f.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8718853018517",
    "item": "Hydraulic bottle jack (lifting jack) â€” 2.0 ton",
    "brand": "Bottle Jack",
    "model": "Hydraulic Bottle Jack 2.0 Ton (Art. 9200264)",
    "category": "Equipment",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/b7ac9752-2673-466c-96e9-1a4fd415209d.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "4019641025972",
    "item": "Car battery charger (6V/12V) with LED control display",
    "brand": "Ultimate Speed",
    "model": "KFZ-BatterieladegerÃ¤t ULG 3.8 A1)",
    "category": "Equipment",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/c7ced2e5-8102-47b1-9fbb-9d08851a513c.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "23W4610339",
    "item": "Cordless tool battery charger (for SKIL 20V system)",
    "brand": "SKIL",
    "model": "20V battery charger (plug-in type)",
    "category": "Equipment",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/78500578-17a4-45f5-9689-5c2017452c42.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8718964213603",
    "item": "Jigsaw blades set (15 pcs), T-shank",
    "brand": "ACTION",
    "model": "â€œ15x Jigsaw Bladesâ€ â€“ mixed set (T111B, T111D, T11",
    "category": "Equipment",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/3d056b34-5664-451d-8f22-7f4881d275dd.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "AQR2410705",
    "item": "Digital multimeter (with test leads)",
    "brand": "Laserliner",
    "model": "MultiMeter ECO",
    "category": "Equipment",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/eade9ab4-1e05-462d-acde-b913f75abd41.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "4007871960545",
    "item": "20V Li-ion rechargeable battery pack (4.0Ah)",
    "brand": "LUX-TOOLS",
    "model": "AK-20/4.0 â€” High Performance (1 PowerSystem max. 2",
    "category": "Equipment",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/7fea09a5-f3b5-44e8-8509-535c79e40dc4.jpg",
    "serialNo": "4007871960521",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "5010559916481",
    "item": "WiFi inspection endoscope camera (waterproof; smartphone-compatible)",
    "brand": "Draper",
    "model": "WiFi Endoscope â€” 91648 Finish/Color: Black",
    "category": "Equipment",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/572b9c01-6db5-4927-ab3a-384f6dea7391.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "7311490055863",
    "item": "Sandpaper roll",
    "brand": "FSC",
    "model": "Sand paper roll â€” 12 cm Ã— 5 m â€” Grit 120 (Medium)",
    "category": "Filler & Putty",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/9b76f79d-cb1c-4d71-811c-2e36866139ab.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8711113911085",
    "item": "Wood filler",
    "brand": "TCX",
    "model": "Wood repair filler",
    "category": "Filler & Putty",
    "type": "Consumable",
    "qty": 3,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/09ae99e4-0d5c-4d56-b4b1-c9d81a13d7ba.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8710345880992",
    "item": "Eurocol 880",
    "brand": "Eurocol ",
    "model": "Eurocol 880 euroseal silicone",
    "category": "Sealant",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/6b81a463-c169-460d-a394-96de921a7b2c.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8718347111090",
    "item": "360 HIGH-TACK (Solvent-Free Hybrid)",
    "brand": "Seal-It",
    "model": "360 HIGH-TACK (Solvent-Free Hybrid)",
    "category": "Sealant",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/2a85e164-3a6e-4733-81c3-4adfcd78a48b.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "5411183179509",
    "item": "PU foam) â€” gap filling & insulation",
    "brand": "TCX",
    "model": "Construction Foam (straw/applicator nozzle) â€” 750 ",
    "category": "Sealant",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/bd2bb9cc-37e8-4b64-8f50-8c69f90ca664.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "4064824002943",
    "item": "Epoxy resin hardener (Part B) for clear casting/coating",
    "brand": "EPODEX",
    "model": "2-component (2K) epoxy system",
    "category": "Sealant",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/6f5e16bc-7fc6-470d-aec0-866d85d3fcbe.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8711247153528",
    "item": "Acrylic sealant / acrylic caulk (paintable; for filling small cracks and joints)",
    "brand": "OK",
    "model": "Acrylaat Kit (French: Mastic Acrylique) â€” paintabl",
    "category": "Equipment",
    "type": "Tool",
    "qty": 6,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/4af6d3b2-c7ae-41a9-9e49-67c2ad23a243.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8711595217040",
    "item": "Silicone sealant / sanitary silicone caulk (flexible, waterproof sealing for joints)",
    "brand": "Den Braven",
    "model": "Siliconenkit â€“ Sanitair (sanitary silicone sealant",
    "category": "Equipment",
    "type": "Tool",
    "qty": 5,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/c009f5fd-a50b-4073-9b88-ced1b21c0ab1.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8711113126076",
    "item": "Exterior wood stain / protective wood finish for doors & window frames (weather-resistant, long-last",
    "brand": "CetaBever (AkzoNobel)",
    "model": "Buiten Deur & Kozijn â€“ Meesterbeits (transparent e",
    "category": "Equipment",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/4a35f60e-fdaa-46ac-b971-1555afecc70b.jpg",
    "serialNo": "8711113126076",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8711113911092",
    "item": "Ready-mix wall filler / crack & hole repair filler (quick-drying, paintable)",
    "brand": "TCX",
    "model": "Instant Filler â€“ White (bucket/paste filler)",
    "category": "Equipment",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/3aee779b-6e3a-4fec-94ea-837945614cc7.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8711247191155",
    "item": "Palm/detail sander (hand sander) â€“ for sanding corners/edges and small surfaces",
    "brand": "GAMMA",
    "model": "Handpalmschuurmachine / Ponceuse de dÃ©tail â€“ HPS-2",
    "category": "Equipment",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/85bc9b58-6fac-4e68-b8cc-5b02ff4a837e.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8711247186908",
    "item": "Wall primer / pre-coat fixer | Transparent â€” coverage approx. Â± 40 mÂ²",
    "brand": "GAMMA",
    "model": "Voorstrijk Primer â€“ Fixeer / Fixation (transparent",
    "category": "Equipment",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/b5557b4c-4320-45e3-adf7-d76c6048c3cc.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8711149002238",
    "item": "Ready-mix joint filler & finishing compound for drywall (Gyproc plasterboard)| White paste (filler/f",
    "brand": "Gyproc (Saint-Gobain)",
    "model": "Vul & Finish (ready-to-use jointing compound)",
    "category": "Equipment",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8711247718390",
    "item": "Manual tile cutter (small model)|Cutting Tool",
    "brand": "GAMMA",
    "model": "Tegelsnijder klein (French: Coupe-carrelage petit)",
    "category": "Equipment",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/6a4cf45a-bbfd-4209-98a1-e7fe2a19beba.jpg",
    "serialNo": "1",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "71607290",
    "item": "White Paint",
    "brand": "",
    "model": "",
    "category": "Paint",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/6106f5ba-9d30-4769-9c0a-e23b685cf434.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8711247019312",
    "item": "Interior satin enamel / lacquer paint (wood/trim paint)",
    "brand": "OK",
    "model": "Zijdeglanslak (French: Laque satinÃ©e), 1L",
    "category": "Paint",
    "type": "Consumable",
    "qty": 13,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/383a2cee-2025-42a5-b336-82e217afaadc.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8711247001522",
    "item": "GAMMA Wood & Wall â€“ Klassiek / Classique (Extra Mat)",
    "brand": "GAMMA",
    "model": "Wood & Wall â€“ Klassiek/Classicque Extra Mat",
    "category": "Paint",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/bc953a3d-f758-4fdc-9120-af5504bd06b3.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8711247020226",
    "item": "white primer/grondverf",
    "brand": "GAMMA",
    "model": "",
    "category": "Paint",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/8acde368-8d27-4bc4-9a39-064ad8850f22.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8716242906728",
    "item": "Wood enamel / wood lacquer paint (scratch & wear resistant) u",
    "brand": "Histor",
    "model": "Perfect Finish â€“ Houtlak (French: Laque pour bois)",
    "category": "Paint",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/623e3143-cd28-4d2c-903c-c6faaa3a5a06.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "87111130996",
    "item": "Interior enamel/trim paint (smooth â€œlacquerâ€ paint)",
    "brand": "Flexa",
    "model": "Strak in de Lak â€” Binnen (color: Goud / Gold)",
    "category": "Paint",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/a41eff8f-4761-4474-a8d8-60296cb615f5.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "5204410811033",
    "item": " (for cleaning brushes + thinning solvent-based paints) u",
    "brand": "Vitex",
    "model": "T-300 (Brush Solvent / Diluent Universal T-300)",
    "category": "Cleaner",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/529fcdce-0003-4632-9d6b-ebd9b0315df2.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8710439305370",
    "item": "Sanitary silicone sealant (for joints in bathrooms/kitchens)",
    "brand": "Griffon",
    "model": "SILPAT (DVGW / EN 751-2",
    "category": "Sealant",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/50b2d1b2-aa8f-4059-84d6-66bd18c5c4f8.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8710345008822",
    "item": "Ready-mixed wall tile adhesive (tile paste)",
    "brand": "Eurocol",
    "model": "690 Tegelpasta (pasteuze wandtegelijm)",
    "category": "Adhesive",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/47d96291-e6d6-4b89-ba78-0d7d59639580.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8711247958888",
    "item": "High-gloss paint/lacquer (tint base)",
    "brand": "Leurtster",
    "model": "Lakverf / Laque â€“ Hoogglans (TR)",
    "category": "Paint",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/f4b2e069-5686-497d-8635-7c06e5c2064e.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8711113869102",
    "item": "Wood oil (water-based) â€“ semi-transparent â€œBangkiraiâ€",
    "brand": "Spectrum",
    "model": "Wood Oil (Semi Transparent â€“ Bangkirai) ",
    "category": "Wood Oil/Finish",
    "type": "Consumable",
    "qty": 16,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/f2c9e170-2220-4e39-a736-f49506128006.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "07235023",
    "item": "Verfafbijt, Paint remover / paint stripper (removes existing paint layers)",
    "brand": "GAMMA",
    "model": "Verfafbijt (drip-free)",
    "category": "Paint Remover",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/ba355204-49d5-4a52-aff5-266ab6b43e8a.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8711247002284",
    "item": "Interior lacquer paint (matte finish)",
    "brand": "GAMMA",
    "model": "Lakverf (Interior) â€“ Matte (Mat) â€“ â€œKras- en stoot",
    "category": "Paint",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/4bff2046-6313-47ee-a875-c5d45f760f71.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8711247021643",
    "item": "Outdoor lacquer / exterior gloss paint",
    "brand": "GAMMA",
    "model": "Buitenlak (Exterior lacquer) â€“ High gloss (Hooggla",
    "category": "Paint",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/e29bf26a-0a2c-4f81-98e1-137ece01d6bf.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8711113910040",
    "item": "Clear wood varnish (transparent, matte)",
    "brand": "Spectrum",
    "model": "Water-based (Mat/Transparent)",
    "category": "Cleaner",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/4118c745-2b0c-44f2-a90b-a9c94e0510a3.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "17108328",
    "item": "Wood filler (natural color)",
    "brand": "Alabastine",
    "model": "Houtvuller (Natural/â€œNaturelâ€)",
    "category": "Cleaner",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/e431c824-c08d-4585-bea5-3729bf0f8f16.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "5200106820730",
    "item": "Fireplace / stove glass cleaner (soot remover spray)",
    "brand": "Mister Barbeque",
    "model": "Spray",
    "category": "Cleaner",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/775adc79-022a-42ef-b0e0-fbc25e2e084f.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8711247153559",
    "item": "White mounting adhesive (construction glue)",
    "brand": "OK",
    "model": "Montagekit (solvent-free)",
    "category": "Adhesive",
    "type": "Consumable",
    "qty": 2,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/8637d0cc-1864-4963-8529-94c96cbc5de8.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8711247001737",
    "item": "Interior lacquer paint (matte)",
    "brand": "GAMMA",
    "model": "Lakverf (Mat / Matte, indoor)",
    "category": "Paint",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/20b1e73b-b870-40e1-8cc2-0872fd47d9eb.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8711247003366",
    "item": "Roest Verwijderaar (Rust Remover)",
    "brand": "GAMMA",
    "model": "Muurverf (Mat / Matte)",
    "category": "Wood Oil/Finish",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/fba98d1c-9111-4590-903f-3e9c9a67ef05.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8711577189860",
    "item": "Rust remover (rust removal liquid), 500 ml",
    "brand": "HG",
    "model": "Roest Verwijderaar (Rust Remover) - 500ml",
    "category": "Cleaner",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/bf5dca25-9c20-44fa-977f-9d9392aa6cde.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8711247869177",
    "item": "Matte spray paint (aerosol lacquer), 400 ml",
    "brand": "OK",
    "model": "Spuitlak Mat (matte aerosol lacquer)",
    "category": "Spray",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/89795e90-09b9-49ad-8a95-5aa310fe44bc.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8711577190439",
    "item": "Professional oven, grill & BBQ cleaner (foam spray)",
    "brand": "XG2",
    "model": "Oven/Grill/BBQ Reiniger (foam spray)",
    "category": "Spray",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/5eced6a0-6dcc-4621-bc2a-2d04e8358122.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8718801357057",
    "item": "Professional oven, grill & BBQ cleaner (foam spray)",
    "brand": "XG2",
    "model": "Oven/Grill/BBQ Reiniger (foam spray)",
    "category": "Spray",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/76344574-33bb-47d4-a5c1-eaca3f7f2e6c.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "4056232545792",
    "item": "Bicycle chain cleaner spray (removes dirt & grease)",
    "brand": "Powerfix Profi+",
    "model": "Kettenreiniger (400 ml)",
    "category": "Spray",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/ae544652-913a-436a-94b5-7ef5615bf09b.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8711247049111",
    "item": "Exterior primer paint (white)",
    "brand": "GAMMA",
    "model": "Grondverf / Primer (voor buiten)",
    "category": "Paint",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/aa12eaf1-8287-4201-83cc-b5190dd7bad4.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8711247026662",
    "item": "Outdoor wood stain (shed & garden house), transparent mahogany",
    "brand": "GAMMA",
    "model": "Tuinbeits (Lasur pour extÃ©rieur) â€“ â€œtuinhuis en sc",
    "category": "Wood Stain",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/29e2e0b1-6fe8-4226-b896-4a741150f7ae.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8710839110277",
    "item": "Super floor-glue remover (for removing tough adhesive residues)",
    "brand": "Alabastine (AkzoNobel)",
    "model": "Super Vloerlijmafbijt",
    "category": "Adhesive",
    "type": "Consumable",
    "qty": 2,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/796cd24d-b7dd-4e26-84b4-32c702e7be5c.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8716242902096",
    "item": "Interior wood lacquer (high gloss)",
    "brand": "Sigma Coatings",
    "model": "Houtlak / Laque Interieur â€“ Hoogglans (Brillant)",
    "category": "Wood Oil/Finish",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/a004d8ec-27c9-424c-87e4-4cb54a209bda.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8711113911818",
    "item": "Interior wall paint (tint base)",
    "brand": "SPS",
    "model": "Collections Muurverf â€“ Basis 00",
    "category": "Wood Oil/Finish",
    "type": "Consumable",
    "qty": 2,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/7bb8795b-0fa5-4c0c-98d8-0a6b001b1bcd.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "7711154704968",
    "item": "Flexa Interior wall paint (tint base)",
    "brand": "AkzoNobel",
    "model": "Collections Muurverf â€“ Basis W00/W05",
    "category": "Paint",
    "type": "Consumable",
    "qty": 3,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/d866de13-265f-4db0-87ed-b081e409b5dc.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "00464404",
    "item": "Wood lacquer / wood varnish (White)",
    "brand": "Histor",
    "model": "Houtlak (Perfect Finish) â€“ White",
    "category": "Wood Oil/Finish",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/7026edfa-1c36-41e0-a3ec-afb5983c70b0.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8711113911436",
    "item": "Water-based 2-in-1 gloss paint (Black)",
    "brand": "Spectrum",
    "model": "2-in-1 Gloss Paint (primer + finish), Black",
    "category": "Paint",
    "type": "Consumable",
    "qty": 2,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/6dcf4a63-56e8-41f3-bc8c-982fa4a3cd7b.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8710259020187",
    "item": "Chrome effect decorative spray paint (Gold)",
    "brand": "Chrome",
    "model": "Deco Spray â€“ Gold, 200 ml",
    "category": "Spray",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/713d3caf-12f0-4e92-a717-72a816d7f925.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8710259020118",
    "item": "Chrome effect decorative spray paint (Silver)",
    "brand": "Chrome",
    "model": "Deco Spray â€“ Silver, 200 ml",
    "category": "Spray",
    "type": "Consumable",
    "qty": 2,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/17caae03-b900-4cf0-9932-4858cb729348.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8716242888192",
    "item": "Rambo, Clear protective varnish (wood)",
    "brand": "Rambo",
    "model": "Pantser Vernis â€“ Colorless (Kleurloos 0000), Satin",
    "category": "Wood Oil/Finish",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/33ca3473-f355-4e5c-bbd8-2d048840abb3.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8711297466623",
    "item": "Clear Primer / Sealer (Interior)",
    "brand": "OK",
    "model": "Voorstrijk Transparant (2.5L)",
    "category": "Sealant",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/e07d9c6b-d45b-4e2d-9f5e-604d4bdedbaf.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "2329747298098",
    "item": "Meister Polar â€“ Wit Plus. Wall/ceiling paint (â€œmuurverfâ€)",
    "brand": "Hornbach",
    "model": "1L",
    "category": "Furniture and fixtures",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/1937090c-5294-407e-a822-81a93e6ee9fb.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "4004014972328",
    "item": "2-in-1 Wood Paint (primer + topcoat in one), Urban Green",
    "brand": "Spectrum",
    "model": "Urban Green, Water-based, Matte",
    "category": "Paint",
    "type": "Consumable",
    "qty": 4,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/eea9c671-65e4-4a2f-9367-ca462a1c793d.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8711247019459",
    "item": "Zijdeglanslak (satin/gloss â€œlacquerâ€ paint), 1L",
    "brand": "OK",
    "model": "1L, about Â±16 mÂ² (per coat, depending on surface)",
    "category": "Paint",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/66f3e759-cca6-4119-a35c-1ce78d2361f4.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8711113911399",
    "item": "2-in-1 Satin paint (primer + finish in one), Water-based (low odour, quick dry)",
    "brand": "Spectrum",
    "model": "RAL 9010 (a common â€œpure/bright whiteâ€)",
    "category": "Paint",
    "type": "Consumable",
    "qty": 5,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/cc12c8e7-523d-450b-a6fe-79288d9d8499.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8711577000721",
    "item": "Vloeibare was naturel (natural liquid wax)",
    "brand": "HG",
    "model": "Parket & Hout â€“ Vloeibare Was Naturel, product 65,",
    "category": "Floor Care/Wood & Parquet Wax",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/cd38b96b-bebc-474a-a3d4-12ab4dbe2ea0.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "3418081887774",
    "item": "Acrylic paint (tube), Titanium White",
    "brand": "Van Bleiswijck Holland",
    "model": "Acrylic â€” Titanium White No. 81",
    "category": "Paint",
    "type": "Consumable",
    "qty": 2,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/b4755275-248e-4007-a160-b37f9c7e2556.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "5011867025407",
    "item": "Metaallak (Direct over Roest) = metal paint you can apply directly over rust",
    "brand": "Hammerite",
    "model": "Standgroen (S038), Finish: Hoogglans (high gloss)",
    "category": "Spray",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/8f4a138a-9733-48ee-b76b-f178bc5170ce.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "5411183196285",
    "item": "Roof Repair â€“ Bitumen (Black) (roof/leak sealant)",
    "brand": "TCX",
    "model": "Roof Repair â€“ Bitumen Black, 290 ml",
    "category": "Sealant",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/a23497ae-44d4-41f3-a49a-ca6f01271325.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "2117144970705",
    "item": "Easy to Clean Wallpaint (washable wall paint)",
    "brand": "Spectrum",
    "model": "RAL 9010 (a warm/off-white)",
    "category": "Paint",
    "type": "Consumable",
    "qty": 2,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/e32588de-f1ca-4f4d-9752-34e7a9434845.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8711113127585",
    "item": "Decking & terrace oil (for Bangkirai / hardwood)",
    "brand": "CetaBever",
    "model": "Tuin Vlonder & Terras Bangkirai Olie (Blank â€” tran",
    "category": "Wood Oil/Finish",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/2774d5bb-df53-4757-bfe6-0c6f7b133263.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8717853121265",
    "item": "Pure Tung Oil (Special)",
    "brand": "ACQ",
    "model": "Specials â€“ Pure Tung Oil, 250 m",
    "category": "Wood Oil/Finish",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/9a15f345-9139-43a5-b901-bf0d4f9bb7f8.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8714181480996",
    "item": "Acrylic paint (black)",
    "brand": "Van Bleiswijck Holland (ACTION)",
    "model": "Acrylic â€” Black No. 99",
    "category": "Paint",
    "type": "Consumable",
    "qty": 2,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/439e9eb4-6d74-49c4-89cb-97ee529b0133.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8716462006130",
    "item": "Rolith Professional",
    "brand": "Rolith (Rolith Professional)",
    "model": "RB1 (Kalk- en cementsluierverwijderaar) â€” 1000 ml",
    "category": "Cleaner",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/af3b9e7e-421f-4277-9bda-2a546a36a6fa.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8711347243600",
    "item": "Decorative effect spray paint (bronze look)",
    "brand": "MOTIP",
    "model": "Effect â€“ Bronze (spray paint)",
    "category": "Spray",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/98220116-597d-4169-8256-9fa37502467f.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8711247026747",
    "item": "Binnenbeits (interior wood stain), transparent, color Donker Eiken (Dark Oak).",
    "brand": "GAMMA",
    "model": "",
    "category": "Wood Stain",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/8a6c2639-9900-46f4-b73a-0929eba5d3ce.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8711247869191",
    "item": "OK Spuitlak Hoogglans (spray lacquer/paint, high gloss), 400 ml",
    "brand": "Ok",
    "model": "",
    "category": "Spray",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/f784f086-6f17-4eb6-a652-109eac2a4d4d.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8715743013195",
    "item": "Rust-Oleum CombiColor Original Spray Paint (Gloss), RAL 9006",
    "brand": "Rust-Oleum",
    "model": "Color: White aluminium / silver-grey(metallic)",
    "category": "Spray",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/87630ab2-2c85-4eae-af5a-c6c3f2a69f2b.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "5011867042862",
    "item": "Radiator Paint (spray) â€” High Gloss, White",
    "brand": "Hammerite (AkzoNobel)",
    "model": "Radiatorlak (spray paint)",
    "category": "Spray",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/244d5674-4774-46b9-8fb2-508c28b6d0d7.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8711595189842",
    "item": "Paint Stripper Spray",
    "brand": "Den Braven (Zwaluw",
    "model": "Afbijtspray â€” P6118 Maintenance",
    "category": "Paint Remover",
    "type": "Consumable",
    "qty": 2,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/3afad790-94b7-4090-b401-22654e647e22.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8710259022259",
    "item": "Spectrum Clear Varnish (Matte) â€“ Spray",
    "brand": "SPECTRUM",
    "model": "Clear Varnish Matt â€” spray paint",
    "category": "Paint",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/ea55eba3-962c-4ca8-b1b7-4585a5b3001c.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "9718577000477",
    "item": "HG Mold Remover / Mold Cleaner",
    "brand": "HG",
    "model": "Schimmel Reiniger (Bathroom) â€” spray bottle 500 ml",
    "category": "Cleaner",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/b4e5b306-f68f-42b6-8ce6-376cc483e274.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8718951545267",
    "item": "Ajax All-Purpose Cleaner (Floor Cleaner) â€“ Energizing Freshness (Lime & White Tea)",
    "brand": "AJAX",
    "model": "",
    "category": "Cleaner",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/afdb2e24-4316-478e-aab2-4c0a7ccb05b4.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "5410091325879",
    "item": "Pattex Wood Glue Waterproof (D3)",
    "brand": "Pattex (Henkel)",
    "model": "",
    "category": "Adhesive",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/c0b5ee83-6efa-4e54-bca8-d12f15898cb8.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8719992551163",
    "item": "Super Degreaser",
    "brand": "Airolube",
    "model": "Super Degreaser â€” spray bottle 500 ml",
    "category": "Cleaner",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/0eb788fc-a4e8-4fd0-8637-056e91619388.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8710259022938",
    "item": "Primer spray paint (spray primer)",
    "brand": "SPECTRUM",
    "model": "Primer spray paint â€” matt, grey",
    "category": "Paint",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/338f348b-5b6e-4e49-9bbc-14c5efb67a99.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8711577308728",
    "item": "Mold Protector (anti-mould protective spray)",
    "brand": "HG",
    "model": "",
    "category": "Spray",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/1fa50bb8-6cce-4a2f-b55f-8cb6a2cfdecc.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8711577000417",
    "item": "Mould Cleaner / Mold Remover (for damp & weather stains)",
    "brand": "HG",
    "model": "",
    "category": "Cleaner",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/ff7a1486-cbd5-4efb-891d-6c8fd9da9fb5.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8711577190088",
    "item": "Insect Remover (insect stain remover / bug remover for vehicles)",
    "brand": "HG",
    "model": "Insecten Verwijderaar / DÃ©col Insectes, spray bott",
    "category": "Cleaner",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/b7e33413-7635-42d9-bce0-b22e4bc93ed3.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "7242029411815",
    "item": "Clear Varnish (for wood)",
    "brand": "SPECTRUM",
    "model": "",
    "category": "Paint",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/e990a9d4-62a6-403b-a528-412816806305.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8711113911443",
    "item": "2-in-1 Matt Paint (primer + topcoat in one)",
    "brand": "SPECTRUM",
    "model": "",
    "category": "Paint",
    "type": "Consumable",
    "qty": 2,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/7dcae10f-fa1d-4ae3-884b-11f2be710094.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8711613875474",
    "item": "concealed cabinet hinge with spring",
    "brand": "HANDSON",
    "model": "",
    "category": "Door/Hardware",
    "type": "Tool",
    "qty": 2,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/fea84959-b21b-446a-b0a2-d49853d043fc.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "9002843412867",
    "item": "cabinet/door handle (pull handle)",
    "brand": "SIRO",
    "model": "",
    "category": "Door/Hardware",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/eb6cd903-c890-4af8-ac88-20a836d52afe.jpg",
    "serialNo": "1 Item",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "88785127A00000050",
    "item": "Big roller wheels",
    "brand": "",
    "model": "",
    "category": "Furniture and fixtures",
    "type": "Tool",
    "qty": 8,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/abcbb4a1-30d0-4ab9-88bf-bb01aa30351e.jpg",
    "serialNo": "8 big roller wheels",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "4042448885029",
    "item": "Tesa Protect, Furniture felt pads / floor protectors (round), extra strong (12 pcs)",
    "brand": "TESA",
    "model": "tesa Protect â€“ Ã˜ 22 mm, black, 12x",
    "category": "Furniture and fixtures",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/69c28872-de31-436f-b62b-bac62d3eef85.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8711247000006",
    "item": "self-adhesive furniture felt pads (48 pcs), white.",
    "brand": "Handson",
    "model": "Meubelvilt zelfklevend wit (48 stuks)",
    "category": "Furniture and fixtures",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/37452b0f-06dc-4d8e-bd63-7b3adccfe4e7.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8711247795988",
    "item": "M5 Rampa nuts / threaded insert nuts (zinc-plated).",
    "brand": "Gamma",
    "model": "M5 Rampamoer, verzinkt (galvanized), 10x",
    "category": "Furniture and fixtures",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/a26aa9be-14d3-448e-81a6-a477819d6a86.jpg",
    "serialNo": "7 Screws",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8718848229751",
    "item": "Broom holder clamp (size M), white.",
    "brand": "Duraline ",
    "model": "",
    "category": "Furniture and fixtures",
    "type": "Tool",
    "qty": 8,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/0a075ea5-983f-43e1-8a5a-cac568b07dbc.jpg",
    "serialNo": "8 clamps",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8715342043913",
    "item": "Plate-mounted swivel caster set (4 pcs)",
    "brand": "Dayes",
    "model": "",
    "category": "Furniture and fixtures",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/58dac46f-104a-44db-bfc4-749a20f0127a.jpg",
    "serialNo": "4 roller wheels (4 Spare Wheels)",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8712259060057",
    "item": "conduit junction box (5/8\")",
    "brand": "",
    "model": "",
    "category": "Electrical",
    "type": "Tool",
    "qty": 7,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/1e89d94a-6ac3-4b09-8a3a-58e5b3a47bec.jpg",
    "serialNo": "6 Pieces",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "4008224669016",
    "item": "Cable trunking end piece ",
    "brand": "Heinrich Kopp",
    "model": "",
    "category": "Electrical",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/e3526ed1-4de0-4c37-af35-3e816d010e76.jpg",
    "serialNo": "1 Item",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "4008224605182",
    "item": "Empty junction box (89 Ã— 43 mm) / inline splice box",
    "brand": "Heinrich Kopp",
    "model": "",
    "category": "Electrical",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/e4ad0369-d832-4739-bc3a-a3641636900a.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8712507131461",
    "item": "IP65 waterproof junction box / weatherproof junction box).",
    "brand": "ABB",
    "model": "Kabeldoos 3665B (supplied with 4 cable glands/lock",
    "category": "Electrical",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/a9156510-441a-4b05-96d5-cd2105da3992.jpg",
    "serialNo": "1 Item",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8712259061825",
    "item": "ARTEMA AK1 junction box (IP40)",
    "brand": "ARTEMA",
    "model": "AK1 IP40",
    "category": "Electrical",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/b4225770-c5bb-4800-afd8-ea47e177b624.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8712259061832",
    "item": "ARTEMA AK1 junction box (IP65)",
    "brand": "ARTEMA",
    "model": "",
    "category": "Electrical",
    "type": "Tool",
    "qty": 3,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/ae83e41d-a6c5-4758-952b-9f920a1af014.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8711247964841",
    "item": "GAMMA plug-in wall spotlight",
    "brand": "GAMMA (Verona)",
    "model": "GU10",
    "category": "Electrical",
    "type": "Tool",
    "qty": 2,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/fd8fd6d0-46b0-4493-9cd8-0612afe906a2.jpg",
    "serialNo": "1 Item",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8711297078239",
    "item": "Handson LED spotlight bulb (GU5.3 / MR16)",
    "brand": "Handson",
    "model": "LED GU5.3, 3W (â‰ˆ20W), 207 lm, dimmable",
    "category": "Electrical",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/bab58125-630c-45a8-9112-d10d5ba3d884.jpg",
    "serialNo": "1 Bulb",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "5999570717805",
    "item": "Modee LED Spot MR16 bulb",
    "brand": "modee (smart lighting)",
    "model": "LED Spot MR16, 2700K warm white",
    "category": "Electrical",
    "type": "Tool",
    "qty": 4,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/27e962c7-effb-472a-8406-485f2e4143b7.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8718699762490",
    "item": "Philips LED E27 bulb, Cool White",
    "brand": "Philips",
    "model": "LED E27, EyeComfort, 4000K cool white, 4.5W, 470 l",
    "category": "Electrical",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/0c6adea2-7165-4f00-9551-9c75b34484da.jpg",
    "serialNo": "1 bulb",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "4306517566760",
    "item": "FLAIR LED A67 (E27) dimmable bulb.",
    "brand": "FLAIR",
    "model": "LED A67 / E27, 2700K warm white, 11W, 1521 lm, 220",
    "category": "Electrical",
    "type": "Tool",
    "qty": 3,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/a8c45ccb-3f04-4b44-878d-bf0148cd8f54.jpg",
    "serialNo": "2 bulbs",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8720707000234",
    "item": "Ledvion LED dimmer.",
    "brand": "",
    "model": "",
    "category": "Electrical",
    "type": "Tool",
    "qty": 4,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/fabe88c6-3f47-46e3-bc7c-ae651fb1c82b.jpg",
    "serialNo": "1 Led Dimmer",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "5059303002377",
    "item": "Wessex Electrical GU10 LED spotlight bulb (multi-pack)",
    "brand": "Wessex Electrical",
    "model": "LED GU10, 2700K, 3.6W (â‰ˆ50W), 345 lm",
    "category": "Electrical",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/9b46c1c0-8377-4c45-b9f0-a1dd3eba9490.jpg",
    "serialNo": "2 bulbs",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "22000873",
    "item": "Cable TV Connection",
    "brand": "Technetix",
    "model": "",
    "category": "Electrical",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/39066dc8-f773-492a-b297-60e6c1b32f4c.jpg",
    "serialNo": "3 Items",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "4008224186469",
    "item": "AP-Standard double switch, Arctic White.",
    "brand": "Heinrich Kopp GmbH",
    "model": "",
    "category": "Electrical",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/ab1d7a39-5278-466a-96f5-d234afc9e511.jpg",
    "serialNo": "1 Item",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "4008224186483",
    "item": "Kopp (Heinrich Kopp GmbH) AP-Standard cross switch, Arctic White.",
    "brand": "Heinrich Kopp GmbH",
    "model": "",
    "category": "Electrical",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/ff68b602-1476-455e-b926-85a680b23d13.jpg",
    "serialNo": "1 Item",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "5410288292298",
    "item": "RefLED Superia Retro MR16, LED reflector/spot bulb (MR16 style), daylight",
    "brand": "Sylvania",
    "model": "LED GU5.3, 12V AC/DC, 4.3W (â‰ˆ35W), 380 lm, 36Â°, 65",
    "category": "Electrical",
    "type": "Tool",
    "qty": 3,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/e935f12c-4757-4405-832c-ae7b61ab4882.jpg",
    "serialNo": "1 bulb",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "88785127A0000050",
    "item": "Paper tape",
    "brand": "",
    "model": "",
    "category": "Adhesive",
    "type": "Consumable",
    "qty": 2,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/03f05907-7975-477d-9259-5eb8dc2f4709.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8711247788652",
    "item": "white surface-mounted two-way / single-pole light switch.",
    "brand": "",
    "model": "",
    "category": "Electrical",
    "type": "Tool",
    "qty": 4,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/bbc0868c-161e-4f0f-bc3f-b7ed8c5167cc.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "88785127A0000003",
    "item": "Paper tape",
    "brand": "",
    "model": "",
    "category": "Adhesive",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/847b5ee4-14dc-479b-8043-a77a18ea3524.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "4058408121633",
    "item": "IKEA SOLHETTA LED bulb set (3 pieces).",
    "brand": "IKEA",
    "model": "SOLHETTA LED, 2W, 230 lm (â‰ˆ35W equivalent), energy",
    "category": "Electrical",
    "type": "Tool",
    "qty": 2,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/c08c03f7-a4e9-448d-bc9a-989a2c42362d.jpg",
    "serialNo": "3 bulbs",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8718739073913",
    "item": "Special PL compact fluorescent lamp",
    "brand": "",
    "model": "11W, 830 (warm white), CRI >80, 8000 hours",
    "category": "Electrical",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/cfdbac6c-fa9c-4768-bb21-dbfb8e53fc16.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "88785127A0000026",
    "item": "Light ",
    "brand": "OSRAM",
    "model": "",
    "category": "Electrical",
    "type": "Tool",
    "qty": 2,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/79410a63-2f02-4fe9-89b9-ad4338124382.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "05035700",
    "item": "OSRAM DULUX S 11W",
    "brand": "OSRAM",
    "model": "",
    "category": "Electrical",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/afc89152-d9bc-4d40-af00-71181b70d3fd.jpg",
    "serialNo": "1 Item",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "4050300437545",
    "item": "OSRAM Powerstar HQI-TS 150W/ND (Daylight) metal halide lamp.",
    "brand": "OSRAM",
    "model": "Powerstar HQI-TS, 150W/D (Daylight)",
    "category": "Electrical",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/923cf529-d696-4279-94ef-d432e9a55eee.jpg",
    "serialNo": "1 item",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8710439123349",
    "item": "HARD PVC GLUE 100ml",
    "brand": "BISON",
    "model": "",
    "category": "Adhesive",
    "type": "Consumable",
    "qty": 3,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/861c8a41-e8f4-4f37-b84c-4a7a6665ab7c.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "3838895000068",
    "item": "ETI DII 16A gG 500V fuse links (5-pack)",
    "brand": "ETI",
    "model": "DII, gG, 16A, 500V (Art. 0023124005)",
    "category": "Electrical",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/09e751a8-de96-430d-92f2-ca16a12ca3f3.jpg",
    "serialNo": "5 Items",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8711247039235",
    "item": " holder (pendant fitting) with lead/connector (3 pcs).",
    "brand": "",
    "model": "",
    "category": "Electrical",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/cd7fb362-6d34-47a9-a77a-e7ee81f8c4fb.jpg",
    "serialNo": "2 items",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8711247153368",
    "item": "HandsOn Spray Adhesive (Spray Glue).",
    "brand": "",
    "model": "Handson",
    "category": "Equipment",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/33619004-b7b9-4edd-a63b-6ed208027083.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "4100420018169",
    "item": "Rapid Cleaner",
    "brand": "LIQUI MOLY",
    "model": "Schnell-Reiniger",
    "category": "Cleaner",
    "type": "Consumable",
    "qty": 2,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/0a172d5e-5965-4a00-843f-ccd0cee0d279.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8710128030040",
    "item": "MP LITHEP GREASE EP2, Multi-purpose lithium grease (cartridge)",
    "brand": "KROON OIL",
    "model": "MP Lithep Grease EP2",
    "category": "Lubricant",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/799d6fbe-4bad-4b5b-9ad5-e337ebd5dd17.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "80287989",
    "item": "IKEA LEDARE LED bulb, LED reflector bulb, warm white",
    "brand": "IKEA",
    "model": "E14 LED, 200 lm, 3.6W, 2700K",
    "category": "Electrical",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/cb2b2866-8644-430c-8c87-c476dc9227c5.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "5032227310353",
    "item": "WD-40 Multi-purpose lubricant / penetrating oil spray",
    "brand": "WD-40",
    "model": "WD-40 Multi-Use (spray), 150 ml",
    "category": "Lubricant",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/c2324292-eb2f-4b77-bc85-ede7f2c9d553.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "11782186",
    "item": "Grouting Mortar Additive",
    "brand": "Handson",
    "model": "Voegmiddel / Mortier de jointoyage (for wand- en v",
    "category": "Tiling materials",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/bd5545ce-2e7e-4470-b508-e5b6b9619759.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "88785127",
    "item": "square white ceiling plate (113 Ã— 113 mm).",
    "brand": "Zanza (Hama)",
    "model": "",
    "category": "Electrical",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/adee06b8-d6f5-4c15-921c-d342adfb573f.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8718964200641",
    "item": "LSC Efficient LED â€“ E14 â€“ 3000K Warm White â€“ 470 lumen â€“ 3.4W (3 bulbs).",
    "brand": "LSC - Efficient Led",
    "model": "LSC Efficient LED E14, 3.4W, 470 lumen, 360Â°",
    "category": "Electrical",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/67bd73f5-5143-4ba2-8d1d-b38189714de1.jpg",
    "serialNo": "3 bulbs",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "322298208361",
    "item": "LED Warm Whiteâ€” 2700K",
    "brand": "Philips",
    "model": "Philips LED G4, 1W (â‰ˆ10W), 100 lumen, 12V AC (elec",
    "category": "Electrical",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/1d6c389d-8393-4515-8f58-0be4583a29a1.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8711247169277",
    "item": "HANDSON LED â€“ G4 â€“ dimmable â€“ 2W (â‰ˆ21W) â€“ 200 lumen â€“ helder wit (3000K) â€“ 12V.",
    "brand": "Handson",
    "model": "G4 LED capsule, 2W (â‰ˆ21W equivalent)",
    "category": "Electrical",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/5f66211f-c088-41b2-84dd-581f873672f1.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "B085T6C9V5",
    "item": "Locked door hasp silver 3 inch (2 pack)",
    "brand": "",
    "model": "X002HMFQXB",
    "category": "Door/Hardware",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/8660315d-e273-4adf-8f22-ad1bf85c216d.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "02820118",
    "item": "Surface-mounted cross switch, Arctic White.",
    "brand": "",
    "model": "",
    "category": "Equipment",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/67181979-552f-4489-a029-895d9d915586.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "8710439123363",
    "item": "Hard PVC Glue (250 ML)",
    "brand": "Bison",
    "model": "Hard PVC-Lijm (French: Colle PVC Rigide) â€“ with br",
    "category": "Adhesive",
    "type": "Consumable",
    "qty": 1,
    "status": "",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/be112749-aa42-480b-a2cb-44463a3719ad.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  },
  {
    "id": "6935364072391",
    "item": "Gigabit VPN gateway (network router/firewall)",
    "brand": "TP-Link (Omada)",
    "model": "ER7206 (Omada Gigabit VPN Gateway)",
    "category": "Networking equipment (router/VPN gateway)",
    "type": "Tool",
    "qty": 1,
    "status": "Available",
    "cabinet": "",
    "shelf": "",
    "photoUrl": "https://www.assettiger.com/xp2/MAT/144549/Gallery/4ecded6e-a72e-48ca-92d9-6f291f1af94f.jpg",
    "serialNo": "",
    "checkedOutBy": null,
    "checkedOutAt": null
  }
];
